"""
src/ctxfw/cli/__init__.py — Unified Command Line Interface Package (v3.9.0)
Axiom Manifest Hash: 9845b97331f39b4cb728b0702dd5b56693b5588c1d129a35a9843d5b8ad8d3ca
"""
from ctxfw.cli.main import (
    app,
    build_parser,
    copy_to_clipboard,
    doctor_entrypoint,
    handle_init_cli,
    handle_init_command,
    handle_install_cli,
    install_entrypoint,
    handle_spec_command,
    init_entrypoint,
    inject_agent_mcp_config,
    install_claude_surfaces,
    safe_merge_claude_code_config,
    main,
    resolve_claude_desktop_config_path,
    resolve_cursor_config_path,
    run_doctor_cli,
    run_firewall_cli,
    run_init_mcp_agents,
    run_spec_verify,
    handle_config_command,
    handle_mode_command,
    handle_report_command,
    generate_share_report,
)

__all__ = [
    "app",
    "build_parser",
    "copy_to_clipboard",
    "run_firewall_cli",
    "handle_init_command",
    "handle_init_cli",
    "init_entrypoint",
    "handle_install_cli",
    "install_entrypoint",
    "run_doctor_cli",
    "doctor_entrypoint",
    "run_spec_verify",
    "handle_spec_command",
    "inject_agent_mcp_config",
    "install_claude_surfaces",
    "safe_merge_claude_code_config",
    "resolve_claude_desktop_config_path",
    "resolve_cursor_config_path",
    "run_init_mcp_agents",
    "handle_config_command",
    "handle_mode_command",
    "handle_report_command",
    "generate_share_report",
    "main",
]
